api = "0.6"

[buildpack]
  id = "paketo-buildpacks/pipenv"
  name = "Paketo Pipenv Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pipenv/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2022.4.8?checksum=53562bf69d9e5238f99a1e2101c356746b1c0aefa5dceb9b8a84a5a3e201de0d&download_url=https://files.pythonhosted.org/packages/3a/b3/7a105cab5f3006c4f771615c33a729d723bf8bce04b05d53dae0e32a5efe/pipenv-2022.4.8.tar.gz"
    sha256 = "08fece45753d7d090dc8cf4e95b4ba4710b9cfcb6f4e7a68bc470605855f9d18"
    source = "https://files.pythonhosted.org/packages/3a/b3/7a105cab5f3006c4f771615c33a729d723bf8bce04b05d53dae0e32a5efe/pipenv-2022.4.8.tar.gz"
    source_sha256 = "53562bf69d9e5238f99a1e2101c356746b1c0aefa5dceb9b8a84a5a3e201de0d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/pipenv/pipenv_2022.4.8_linux_noarch_bionic_08fece45.tgz"
    version = "2022.4.8"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:pypa:pipenv:2022.4.20:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2022.4.20?checksum=f9101d3f9a38e9296a33630a5ed29dee4d5f2661d199dd9a60071f0c49f2e432&download_url=https://files.pythonhosted.org/packages/d9/28/3f294795632b4409e68783f02f5b57c16606bffcf22ae9ba203341996e39/pipenv-2022.4.20.tar.gz"
    sha256 = "0b570da3d696551590ff25c839fa2ae849d319ae84f44447a644ed2ed54d9766"
    source = "https://files.pythonhosted.org/packages/d9/28/3f294795632b4409e68783f02f5b57c16606bffcf22ae9ba203341996e39/pipenv-2022.4.20.tar.gz"
    source_sha256 = "f9101d3f9a38e9296a33630a5ed29dee4d5f2661d199dd9a60071f0c49f2e432"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/pipenv/pipenv_2022.4.20_linux_noarch_bionic_0b570da3.tgz"
    version = "2022.4.20"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pipenv"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
