api = "0.6"

[buildpack]
  id = "paketo-buildpacks/pipenv"
  name = "Paketo Pipenv Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pipenv/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:pypa:pipenv:2022.4.21:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2022.4.21?checksum=3f93229de25a4c3a658249f48407b80f347f076640a9fd50c476a2876212f781&download_url=https://files.pythonhosted.org/packages/0b/c5/45624349729103aecbf8c818f1f655d522bcbb9e127ef8e712e78a8b491d/pipenv-2022.4.21.tar.gz"
    sha256 = "c57ef7f5face084b2a5c5177221c07dc26d37c8f5a83617103ac2827abded08f"
    source = "https://files.pythonhosted.org/packages/0b/c5/45624349729103aecbf8c818f1f655d522bcbb9e127ef8e712e78a8b491d/pipenv-2022.4.21.tar.gz"
    source_sha256 = "3f93229de25a4c3a658249f48407b80f347f076640a9fd50c476a2876212f781"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/pipenv/pipenv_2022.4.21_linux_noarch_bionic_c57ef7f5.tgz"
    version = "2022.4.21"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:pypa:pipenv:2022.4.30:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2022.4.30?checksum=e26ded6ab90a7900676a1db9955d5ee714115f443aecc072b09497153ed237c7&download_url=https://files.pythonhosted.org/packages/64/8f/b7fbe585b759b3455d8fc674bc752cbef3c9565940b7342ba70361d50648/pipenv-2022.4.30.tar.gz"
    sha256 = "8f2062e3001de97b3f29355f1a1a3b4daa9c0ac0d7a7bba7c1ebc23ca2735ee6"
    source = "https://files.pythonhosted.org/packages/64/8f/b7fbe585b759b3455d8fc674bc752cbef3c9565940b7342ba70361d50648/pipenv-2022.4.30.tar.gz"
    source_sha256 = "e26ded6ab90a7900676a1db9955d5ee714115f443aecc072b09497153ed237c7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/pipenv/pipenv_2022.4.30_linux_noarch_bionic_8f2062e3.tgz"
    version = "2022.4.30"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pipenv"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
